export const PROVIDER = Object.freeze({
  EMAIL: 1,
  GOOGLE: 2,
  APPLE: 3,
  NAVER: 4,
  KAKAO: 5,
});

export const NAMESPACE = Object.freeze({
  CHAT: 'chat',
  UNIFICATION: 'unification',
});

export const NATS_EVENTS = Object.freeze({
  ENTER_PLAYER_ROOM: 'ENTER_PLAYER_ROOM',
  EXIT_AND_ENTER_PLAYER_ROOM: 'EXIT_AND_ENTER_PLAYER_ROOM',
  EXIT_PLAYER_ROOM: 'EXIT_PLAYER_ROOM',
  PLAYER_MOVE_TRANSFORM: 'PLAYER_MOVE_TRANSFORM',
  CREATE_PLAYER_ROOM: 'CREATE_PLAYER_ROOM',
  DELETE_PLAYER_ROOM: 'DELETE_PLAYER_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  SYNC_ROOM: 'SYNC_ROOM',
  PLAYER_ROOM: 'PLAYER_ROOM',
  MY_ROOM: 'MY_ROOM',

  CREATE_OFFICE: 'CREATE_OFFICE',
  DELETE_OFFICE: 'DELETE_OFFICE',

  SCREEN: 'SCREEN',
  BANNER: 'BANNER',

  COMMON_ROOM: 'COMMON_ROOM',
  CHAT_ROOM: 'CHAT_ROOM',
  CREATE_CHAT_ROOM: 'CREATE_CHAT_ROOM',
  DELETE_CHAT_ROOM: 'DELETE_CHAT_ROOM',
  EXIT_AND_ENTER_CHAT_ROOM: 'EXIT_AND_ENTER_CHAT_ROOM',
  EXIT_CHAT_ROOM: 'EXIT_CHAT_ROOM',

  NATS_CONNECTED: 'NATS_CONNECTED',
  DUPLICATE_LOGIN_USER: 'DUPLICATE_LOGIN_USER',

  REQ_GET_GAMEOBJECTS: 'REQ_GET_GAMEOBJECTS',
  RES_GET_GAMEOBJECTS: 'RES_GET_GAMEOBJECTS',

  START_EDIT_MY_ROOM: 'START_EDIT_MY_ROOM',
  END_EDIT_MY_ROOM: 'END_EDIT_MY_ROOM',
});

export const SOCKET_S_GLOBAL = Object.freeze({
  ERROR: 'ERROR',
  S_SYSTEM_MESSAGE: 'S_SYSTEM_MESSAGE', // 시스템 메시지
  S_DROP_USER: 'S_DROP_USER', // 플레이어 강제 퇴장
  S_USER_CONNECTED: 'S_USER_CONNECTED', // 플레이어 접속
});

// Socket.IO Server -> Client Chatting Message Constants
export const CHAT_SOCKET_S_MESSAGE = Object.freeze({
  S_ENTER: 'S_ENTER', // 룸 입장
  S_SYSTEM_MESSAGE: 'S_SYSTEM_MESSAGE', // 시스템 메시지
  S_SEND_MESSAGE: 'S_SEND_MESSAGE', // 채팅 메시지 보내기

  S_SEND_DIRECT_MESSAGE: 'S_SEND_DIRECT_MESSAGE', // 다이렉트 메시지 보내기
  S_SEND_FRIEND_DIRECT_MESSAGE: 'S_SEND_FRIEND_DIRECT_MESSAGE', // 친구 다이렉트 메시지 보내기
});

// Socket.IO C_ -> S_ Chatting Message Constants
export const CHAT_SOCKET_C_MESSAGE = Object.freeze({
  C_ENTER: 'C_ENTER', // 룸 입장
  C_SEND_MESSAGE: 'C_SEND_MESSAGE', // 채팅 메시지 보내기
  C_RECEIVE_MESSAGE: 'C_RECEIVE_MESSAGE', // 채팅 메시지 받기

  C_SEND_DIRECT_MESSAGE: 'C_SEND_DIRECT_MESSAGE', // 다이렉트 메시지 보내기
  C_RECEIVE_DIRECT_MESSAGE: 'C_RECEIVE_DIRECT_MESSAGE', // 다이렉트 메시지 받기
  C_SEND_FRIEND_DIRECT_MESSAGE: 'C_SEND_FRIEND_DIRECT_MESSAGE', // 친구 다이렉트 메시지 보내기
});
